Gobelijn API documentation: UA_CoMP::Misc::TracerOutput Class Reference
UA_CoMP::Misc::TracerOutput Class Reference
Class used to channel output of the BlockTracer, FunctionTracer and MemberTracer objects to the g3log.
#include <TracerOutput.h>
Public Member Functions
TracerOutput ()=default
No constructor.
bool is_output_on ()
Indicate whether current making output.
void set_output_on ()
Start making output (ok even output already started).
void set_output_off ()
Stop making output (ok even if output already stopped).
void increase_indent ()
Increase the indentation level.
void decrease_indent ()
Decrease the indentation level.
void log (const std::string &msg)
Insert the message in the google log at given severity level.
Private Attributes
bool m_make_output {true}
unsigned int m_indent {0}
Detailed Description
Class used to channel output of the BlockTracer, FunctionTracer and MemberTracer objects to the g3log.
Manages the following features for the Tracer object's output:
on or off status of producing output to the log
the indentation levels when blocks get nested
Definition at line 29 of file TracerOutput.h.
Constructor & Destructor Documentation
UA_CoMP::Misc::TracerOutput::TracerOutput () default
No constructor.
Member Function Documentation
bool UA_CoMP::Misc::TracerOutput::is_output_on ()
Indicate whether current making output.
Definition at line 17 of file TracerOutput.cpp.
void UA_CoMP::Misc::TracerOutput::set_output_on ()
Start making output (ok even output already started).
Definition at line 19 of file TracerOutput.cpp.
void UA_CoMP::Misc::TracerOutput::set_output_off ()
Stop making output (ok even if output already stopped).
Definition at line 21 of file TracerOutput.cpp.
void UA_CoMP::Misc::TracerOutput::increase_indent ()
Increase the indentation level.
Definition at line 23 of file TracerOutput.cpp.
Referenced by UA_CoMP::Misc::BlockTracer::BlockTracer(), UA_CoMP::Misc::FunctionTracer::FunctionTracer(), and UA_CoMP::Misc::MemberTracer::MemberTracer().
void UA_CoMP::Misc::TracerOutput::decrease_indent ()
Decrease the indentation level.
Definition at line 25 of file TracerOutput.cpp.
Referenced by UA_CoMP::Misc::BlockTracer::~BlockTracer(), UA_CoMP::Misc::FunctionTracer::~FunctionTracer(), and UA_CoMP::Misc::MemberTracer::~MemberTracer().
void UA_CoMP::Misc::TracerOutput::log (const std::string & msg)
Insert the message in the google log at given severity level.
Definition at line 27 of file TracerOutput.cpp.
Referenced by UA_CoMP::Misc::BlockTracer::BlockTracer(), UA_CoMP::Misc::FunctionTracer::FunctionTracer(), UA_CoMP::Misc::MemberTracer::MemberTracer(), UA_CoMP::Misc::BlockTracer::~BlockTracer(), UA_CoMP::Misc::FunctionTracer::~FunctionTracer(), and UA_CoMP::Misc::MemberTracer::~MemberTracer().
Member Data Documentation
bool UA_CoMP::Misc::TracerOutput::m_make_output {true} private
Definition at line 54 of file TracerOutput.h.
unsigned int UA_CoMP::Misc::TracerOutput::m_indent {0} private
Definition at line 55 of file TracerOutput.h.
The documentation for this class was generated from the following files:
TracerOutput.h
TracerOutput.cpp