Gobelijn API documentation: ODemo::PassengerRoadVehicle Class Reference
ODemo::PassengerRoadVehicle Class Reference
A PassengerRoadVehicle transports one or more passengers.
#include <PassengerRoadVehicle.h>
Public Member Functions
PassengerRoadVehicle (int numSeats)
Parametrized constructor, initializes number of seats.
PassengerRoadVehicle (PassengerRoadVehicle const &ori)
Copy constructor.
PassengerRoadVehicle (PassengerRoadVehicle &&ori) noexcept
Move constructor.
PassengerRoadVehicle & operator= (PassengerRoadVehicle const &rhs)
Copy assignment.
PassengerRoadVehicle & operator= (PassengerRoadVehicle &&rhs) noexcept
Move assignment.
~PassengerRoadVehicle () override
Destructor.
bool add_passenger ()
Take an additional passenger on board, if possible.
bool remove_passenger ()
Remove a passenger, if possible.
int get_capacity () const
Return the number of seats on the vehicle.
int get_free () const
Return the number of seats still free.
void info () const override
Return identification info.
Public Member Functions inherited from ODemo::RoadVehicle
RoadVehicle ()
Default constructor.
RoadVehicle (const RoadVehicle &ori)
Copy constructor.
RoadVehicle (RoadVehicle &&ori) noexcept
Move constructor.
RoadVehicle & operator= (const RoadVehicle &rhs)
Copy assignment operator.
RoadVehicle & operator= (RoadVehicle &&rhs) noexcept
Move assignment operator.
~RoadVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Motion of the vehicle.
Public Member Functions inherited from ODemo::LandVehicle
LandVehicle ()
default constructor.
LandVehicle (const LandVehicle &ori)
Copy constructor.
LandVehicle (LandVehicle &&ori) noexcept
Move constructor.
LandVehicle & operator= (const LandVehicle &rhs)
Copy assignment.
LandVehicle & operator= (LandVehicle &&rhs) noexcept
Move assignment.
~LandVehicle () override
Destructor.
Public Member Functions inherited from ODemo::Vehicle
virtual ~Vehicle ()=default
Destructor.
Private Attributes
int m_capacity
int m_free
Detailed Description
A PassengerRoadVehicle transports one or more passengers.
Definition at line 15 of file PassengerRoadVehicle.h.
Constructor & Destructor Documentation
ODemo::PassengerRoadVehicle::PassengerRoadVehicle (int numSeats) explicit
Parametrized constructor, initializes number of seats.
Definition at line 18 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
ODemo::PassengerRoadVehicle::PassengerRoadVehicle (PassengerRoadVehicle const & ori)
Copy constructor.
Definition at line 23 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
ODemo::PassengerRoadVehicle::PassengerRoadVehicle (PassengerRoadVehicle && ori) noexcept
Move constructor.
Definition at line 29 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
ODemo::PassengerRoadVehicle::~PassengerRoadVehicle () override
Destructor.
Definition at line 57 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
PassengerRoadVehicle & ODemo::PassengerRoadVehicle::operator= (PassengerRoadVehicle const & rhs)
Copy assignment.
Definition at line 35 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, m_capacity, m_free, and ODemo::RoadVehicle::operator=().
Referenced by ODemo::Bicycle::operator=().
PassengerRoadVehicle & ODemo::PassengerRoadVehicle::operator= (PassengerRoadVehicle && rhs) noexcept
Move assignment.
Definition at line 46 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, m_capacity, m_free, and ODemo::RoadVehicle::operator=().
bool ODemo::PassengerRoadVehicle::add_passenger ()
Take an additional passenger on board, if possible.
Definition at line 59 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_free.
Referenced by app_hierarchies().
bool ODemo::PassengerRoadVehicle::remove_passenger ()
Remove a passenger, if possible.
Definition at line 70 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, m_capacity, and m_free.
int ODemo::PassengerRoadVehicle::get_capacity () const
Return the number of seats on the vehicle.
Definition at line 81 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_capacity.
int ODemo::PassengerRoadVehicle::get_free () const
Return the number of seats still free.
Definition at line 87 of file PassengerRoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_free.
void ODemo::PassengerRoadVehicle::info () const override virtual
Return identification info.
Reimplemented from ODemo::LandVehicle.
Definition at line 93 of file PassengerRoadVehicle.cpp.
References COMP_MISC_LOG_TRACER, COMP_MISC_MEMBER_TRACER, m_capacity, m_free, and UA_CoMP::Util::StringUtils::ToString().
Member Data Documentation
int ODemo::PassengerRoadVehicle::m_capacity private
Definition at line 52 of file PassengerRoadVehicle.h.
Referenced by get_capacity(), info(), operator=(), and remove_passenger().
int ODemo::PassengerRoadVehicle::m_free private
Definition at line 53 of file PassengerRoadVehicle.h.
Referenced by add_passenger(), get_free(), info(), operator=(), and remove_passenger().
The documentation for this class was generated from the following files:
PassengerRoadVehicle.h
PassengerRoadVehicle.cpp