Gobelijn API documentation: Raii::File Class Reference
Raii::File Class Reference
A wrapper around the C FILE*-based IO API.
#include <file.h>
Public Member Functions
File ()=delete
File (const File &)=delete
File & operator= (const File &)=delete
File (const char *path, const char *mode)
Opens the file at the given path.
File (File &&other) noexcept
Creates a new file object from the file object's resources.
File & operator= (File &&other)
Moves the given file object's resources to this file object.
~File ()
Performs clean-up for this File instance.
void Close ()
Closes this file resource.
bool IsOpen () const
Checks if this file is still open.
int ReadChar ()
Reads the next input character from this file.
void WriteChar (char Value)
Writes a single character to the file.
Private Member Functions
bool CloseImpl ()
Closes this file resource.
Private Attributes
std::FILE * m_file
Detailed Description
A wrapper around the C FILE*-based IO API.
Note: this is a header-only class.
Definition at line 47 of file file.h.
Constructor & Destructor Documentation
Raii::File::File () delete
Raii::File::File (const File &) delete
Raii::File::File (const char * path, const char * mode) inline
Opens the file at the given path.
Definition at line 56 of file file.h.
References m_file.
Raii::File::File (File && other) inline noexcept
Creates a new file object from the file object's resources.
Definition at line 65 of file file.h.
References m_file.
Raii::File::~File () inline
Performs clean-up for this File instance.
Definition at line 80 of file file.h.
References CloseImpl().
Member Function Documentation
File& Raii::File::operator= (const File &) delete
File& Raii::File::operator= (File && other) inline
Moves the given file object's resources to this file object.
Definition at line 72 of file file.h.
References m_file.
void Raii::File::Close () inline
Closes this file resource.
An exception is thrown if this file cannot be closed properly. Successfully closing a file more than once is a no-op.
Definition at line 90 of file file.h.
References CloseImpl().
Referenced by main().
bool Raii::File::IsOpen () const inline
Checks if this file is still open.
Definition at line 98 of file file.h.
References m_file.
Referenced by CloseImpl(), ReadChar(), and WriteChar().
int Raii::File::ReadChar () inline
Reads the next input character from this file.
'EOF' is returned when the end-of-file has been reached.
Definition at line 102 of file file.h.
References IsOpen(), and m_file.
Referenced by Raii::RandomReadFile::operator[](), and printFile().
void Raii::File::WriteChar (char Value) inline
Writes a single character to the file.
Definition at line 115 of file file.h.
References IsOpen(), and m_file.
Referenced by main().
bool Raii::File::CloseImpl () inline private
Closes this file resource.
A boolean is returned that tells if this resource has been closed properly. Closing a file more than once is OK and will return 'true' every time.
Definition at line 127 of file file.h.
References IsOpen(), and m_file.
Referenced by Close(), and ~File().
Member Data Documentation
std::FILE* Raii::File::m_file private
Definition at line 140 of file file.h.
Referenced by CloseImpl(), File(), IsOpen(), operator=(), ReadChar(), and WriteChar().
The documentation for this class was generated from the following file:
file.h