var annotated =
[
    [ "AbstractFactory", "da/dc8/namespaceAbstractFactory.html", "da/dc8/namespaceAbstractFactory" ],
    [ "ODemo", "d1/d5f/namespaceODemo.html", "d1/d5f/namespaceODemo" ],
    [ "Pimpl", "dd/d5b/namespacePimpl.html", "dd/d5b/namespacePimpl" ],
    [ "Raii", "d9/dea/namespaceRaii.html", "d9/dea/namespaceRaii" ],
    [ "UA_CoMP", "d4/d69/namespaceUA__CoMP.html", "d4/d69/namespaceUA__CoMP" ],
    [ "Accum", "df/d08/classAccum.html", "df/d08/classAccum" ],
    [ "AccumulationTraits", "da/d52/classAccumulationTraits.html", null ],
    [ "AccumulationTraits< char >", "de/da3/classAccumulationTraits_3_01char_01_4.html", "de/da3/classAccumulationTraits_3_01char_01_4" ],
    [ "AccumulationTraits< float >", "de/de1/classAccumulationTraits_3_01float_01_4.html", "de/de1/classAccumulationTraits_3_01float_01_4" ],
    [ "AccumulationTraits< int >", "d7/dfd/classAccumulationTraits_3_01int_01_4.html", "d7/dfd/classAccumulationTraits_3_01int_01_4" ],
    [ "AccumulationTraits< short >", "d8/d65/classAccumulationTraits_3_01short_01_4.html", "d8/d65/classAccumulationTraits_3_01short_01_4" ],
    [ "AccumulationTraits< unsigned int >", "dc/dfa/classAccumulationTraits_3_01unsigned_01int_01_4.html", "dc/dfa/classAccumulationTraits_3_01unsigned_01int_01_4" ],
    [ "CellCountPolicy", "d6/d66/classCellCountPolicy.html", null ],
    [ "conststr", "d5/d1a/classconststr.html", "d5/d1a/classconststr" ],
    [ "ConvergencePolicy", "d3/d0b/classConvergencePolicy.html", null ],
    [ "Plotter", "d6/de6/classPlotter.html", "d6/de6/classPlotter" ],
    [ "Polynomial", "d8/dd4/classPolynomial.html", "d8/dd4/classPolynomial" ],
    [ "QuadRule1", "d8/d22/classQuadRule1.html", null ],
    [ "QuadRule2", "dd/df7/classQuadRule2.html", null ],
    [ "RandInt", "d9/da9/classRandInt.html", "d9/da9/classRandInt" ],
    [ "Range", "d5/d98/structRange.html", "d5/d98/structRange" ],
    [ "select", "db/d9e/structselect.html", null ],
    [ "select< T1, T2, false >", "dd/d4a/structselect_3_01T1_00_01T2_00_01false_01_4.html", "dd/d4a/structselect_3_01T1_00_01T2_00_01false_01_4" ],
    [ "select< T1, T2, true >", "da/d47/structselect_3_01T1_00_01T2_00_01true_01_4.html", "da/d47/structselect_3_01T1_00_01T2_00_01true_01_4" ],
    [ "smaller", "d5/d17/structsmaller.html", "d5/d17/structsmaller" ],
    [ "Stack", "d4/dc1/classStack.html", "d4/dc1/classStack" ],
    [ "Stack< std::string >", "d5/d70/classStack_3_01std_1_1string_01_4.html", "d5/d70/classStack_3_01std_1_1string_01_4" ],
    [ "SumPolicy", "d7/d3b/classSumPolicy.html", "d7/d3b/classSumPolicy" ],
    [ "SumPolicy< false >", "de/d14/classSumPolicy_3_01false_01_4.html", "de/d14/classSumPolicy_3_01false_01_4" ]
];