Gobelijn API documentation: demos.h File Reference
demos.h File Reference
Header for object tracer demo routines.
Functions
int app_copy ()
Demo prog to demonstrate deep & shallow copy operations.
int app_essentialops ()
Demo prog for features of ctor/dtor.
int app_exception ()
Demo prog for ctor/dtor features in class derivation.
int app_fcalls ()
Demo prog for features of essential ops.
int app_hierarchies ()
Demo prog for ctor/dtor features in class derivation.
int app_poly1 ()
Demonstrates late binding.
int app_poly2 ()
Demonstrates late binding.
Detailed Description
Header for object tracer demo routines.
Author
J. Broeckhove, CoMP/UA
Definition in file demos.h.
Function Documentation
int app_copy ()
Demo prog to demonstrate deep & shallow copy operations.
Returns
status
Exceptions
None.
Definition at line 19 of file app_copy.cpp.
References COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, and ODemo::Motorcycle::stopEngine().
Referenced by main().
int app_essentialops ()
Demo prog for features of ctor/dtor.
Returns
status
Exceptions
None.
Definition at line 22 of file app_essentialops.cpp.
References ODemo::Motorcycle::accelerate(), COMP_MISC_BLOCK_TRACER, COMP_MISC_FUNCTION_TRACER, and COMP_MISC_LOG_TRACER.
Referenced by main().
int app_exception ()
Demo prog for ctor/dtor features in class derivation.
Returns
status
Exceptions
None.
Definition at line 20 of file app_exception.cpp.
References COMP_MISC_BLOCK_TRACER, COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, ODemo::Exception::info(), ODemo::SailBoat::info(), ODemo::Bicycle::info(), ODemo::LoadingException::info(), ODemo::SailingException::info(), ODemo::SailBoat::move(), ODemo::WaterVehicle::start_sinking(), and ODemo::Exception::what().
Referenced by main().
int app_fcalls ()
Demo prog for features of essential ops.
Returns
status
Exceptions
None.
Definition at line 50 of file app_fcalls.cpp.
References COMP_MISC_FUNCTION_TRACER, and COMP_MISC_LOG_TRACER.
Referenced by main().
int app_hierarchies ()
Demo prog for ctor/dtor features in class derivation.
Returns
status
Exceptions
None.
Definition at line 19 of file app_hierarchies.cpp.
References ODemo::PassengerRoadVehicle::add_passenger(), COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, ODemo::Vehicle::info(), ODemo::SailBoat::info(), ODemo::Bicycle::info(), ODemo::SailBoat::move(), and ODemo::WaterVehicle::start_sinking().
Referenced by main().
int app_poly1 ()
Demonstrates late binding.
Returns
status
Exceptions
None.
Definition at line 37 of file app_poly1.cpp.
References COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, COMP_MISC_TRACER_OUTPUT_OFF, and COMP_MISC_TRACER_OUTPUT_ON.
Referenced by main().
int app_poly2 ()
Demonstrates late binding.
Returns
status
Exceptions
None.
Definition at line 37 of file app_poly2.cpp.
References COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, COMP_MISC_TRACER_OUTPUT_OFF, and COMP_MISC_TRACER_OUTPUT_ON.
Referenced by main().